//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryAccounting.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int idUser { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Profession { get; set; }
        public int ServiceNumber { get; set; }
        public int WorkshopNumber { get; set; }
        public int RegionNumber { get; set; }
        public string City { get; set; }
    }
}
